# Generated by Django 5.2 on 2025-04-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название автобуса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='buses/', verbose_name='Изображение')),
                ('rarity', models.IntegerField(choices=[(1, 'Обычный'), (2, 'Необычный'), (3, 'Редкий'), (4, 'Легендарный')], default=1, verbose_name='Редкость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinventory_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвентарь пользователя',
                'verbose_name_plural': 'Инвентари пользователей',
                'unique_together': {('user', 'bus')},
            },
        ),
    ]
